### ISSUE TITLE
FYI: asn.rspamd.com

### ISSUE THREAD

**Issue by smfreegard** [haraka/haraka-plugin-asn#4]
The rspamd devs got so fed-up with cymru.com being down periodically last week that they decided to build their own equivalent service from the raw data:

```
[root@mail1-ewh plugins]# host -t TXT 196.13.69.82.asn.rspamd.com
196.13.69.82.asn.rspamd.com descriptive text "13037|82.68.0.0/14|GB|ripencc|"
```

See https://github.com/vstakhov/rspamd/blob/master/utils/asn.pl

**Comment by msimerson** [comment]
Ah, good to know. We should add that as a DNS source. (It's a low priority for me, I use the geoip database).
